# ./gradlew --no-daemon front50-web:installDist -x test
# docker rmi front50
# docker build -t front50 -f Dockerfile.ubuntu .

FROM ubuntu:bionic
LABEL maintainer="sig-platform@spinnaker.io"
RUN apt-get update && apt-get -y install openjdk-11-jdk openjdk-11-dbg wget

USER root
WORKDIR /root
EXPOSE 8080

#RUN adduser --system --uid 10111 --group spinnaker
COPY front50-web/build/install/front50 /opt/front50
RUN mkdir -p /opt/front50/plugins
#USER spinnaker
CMD ["/opt/front50/bin/front50"]
